#!/usr/bin/env python

import sys

from rqt_basic_sub.basic_sub import BasicSub
from rqt_gui.main import Main

plugin = 'rqt_basic_sub'
main = Main(filename=plugin)
sys.exit(main.main(standalone=plugin))
