dist: xenial
language: python

python:
  - "2.7"
  - "3.6"
  - "3.7"

services:
  - docker

before_install:
  - docker build -t gramaziokohler/rosbridge ./docker
  - docker run -d -p 9090:9090 --name rosbridge gramaziokohler/rosbridge /bin/bash -c "roslaunch /integration-tests.launch"
  - docker ps -a

install:
  - pip install -r requirements-dev.txt

script:
  - isort --check-only --diff --recursive src tests setup.py
  - pytest

after_script:
  - docker rm -f rosbridge
