pure_pursuit:
    lookahead_distance: 0.4
    odometry_topic: "/frcrobot_jetson/swerve_drive_controller/odom"
    target_frame: "initial_pose"
    final_pos_tol: 0.1
    ros_rate: 10
    server_timeout: 5
