swerve_drive_controller:
    steering_joint_bl:
        offset: -2.23041
    steering_joint_br:
        offset: 1.93588
    steering_joint_fl:
        offset: 2.78264
    steering_joint_fr:
        offset: 2.35619

