#Config file for configuring autonomous modes and actions

# CONSTANTS -----------------------------------------------------------------------
goal_to_wall_y_dist: 2.404

# MODES ---------------------------------------------------------------------------
# arrays of actions (see below) that will be executed in order
# format: auto_mode_[integer]: array

auto_mode_1: ["start_intake", "path_to_trench_face_goal", "stop_intake", "shoot", "pause_2_sec"] #example
auto_mode_2: ["pause_2_sec","pause_5_sec"]
auto_mode_3: ["drive_back", "path_to_trench_after_drive_back"]
auto_mode_4: ["drive_back", "shoot", "path_to_trench_after_drive_back"]
auto_mode_5: ["drive_test_angle", "start_intake", "drive_forward", "stop_intake"]

# ACTIONS ------------------------------------------------------------------------
# must have a value for "type", other stuff varies
#valid action types: "intake_actionlib_server", "pause", "elevator_actionlib_server"

#examples:

start_intake:
    type: "intake_actionlib_server"
    goal:
        "start"

stop_intake:
    type: "intake_actionlib_server"
    goal:
        "stop"

shoot:
    type: "shooter_actionlib_server"
    goal:
        ""

drive_back:
    type: "path"
    goal:
        apply_offset: false 
        points:
            - [-0.7, 0.0, 0.0] # move back length of robot

path_to_trench_from_starting:
    type: "path"
    goal:
        apply_offset: true
        points:
            - [-3.0, -1.69938, 0.0] #from starting position to in front of the trench
            - [-4.2, -1.69938, 0.0] #drive toward the trench distance of 2 balls

path_to_trench_after_drive_back:
    type: "path"
    goal:
        apply_offset: true
        points:
            - [-2.3, -1.69938, 0.0] 
            - [-3.5, -1.69938, 0.0]

pause_2_sec:
    type: "pause"
    duration: 2 #sec

pause_5_sec:
    type: "pause"
    duration: 5.0

drive_test_angle:
    type: "path"
    goal:
        apply_offset: false 
        points:
            - [1.0, -1.0, 0.0]
            - [2.0, 0.0, 0.0] 

drive_forward:
    type: "path"
    goal:
        apply_offset: false 
        points:
            - [1.5, 0.0, 0.0]

