topics:
-
  name    : combine orient strafing
  topic   : /teleop/orient_strafing/swerve_drive_controller/cmd_vel
  timeout : 0.2
  priority: 200
-
  name    : teleop joystick comp
  topic   : /teleop/swerve_drive_controller/cmd_vel
  timeout : 0.2
  priority: 175
-
  name    : climber server
  topic   : /climber/swerve_drive_controller/cmd_vel
  timeout : 0.2
  priority: 150
-
  name    : outtake_hatch_panel_server
  topic   : /hatch_outtake/swerve_drive_controller/cmd_vel
  timeout : 0.2
  priority: 100
-
  name    : align_hatch
  topic   : /align_hatch/align_hatch/swerve_drive_controller/cmd_vel
  timeout : 0.2
  priority: 120
-
  name    : path_follower 
  topic   : /path_follower/path_follower_pid/swerve_drive_controller/cmd_vel
  timeout : 0.2
  priority: 130
locks: []
