# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\Dashboard.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1000, 800)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.dashLabel = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dashLabel.sizePolicy().hasHeightForWidth())
        self.dashLabel.setSizePolicy(sizePolicy)
        self.dashLabel.setObjectName("dashLabel")
        self.verticalLayout_4.addWidget(self.dashLabel)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.auto_mode_v_layout = QtWidgets.QVBoxLayout()
        self.auto_mode_v_layout.setObjectName("auto_mode_v_layout")
        self.pubLabel = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pubLabel.sizePolicy().hasHeightForWidth())
        self.pubLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.pubLabel.setFont(font)
        self.pubLabel.setObjectName("pubLabel")
        self.auto_mode_v_layout.addWidget(self.pubLabel)
        self.horizontalLayout.addLayout(self.auto_mode_v_layout)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_2 = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        self.auto_state_display = QtWidgets.QLineEdit(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.auto_state_display.sizePolicy().hasHeightForWidth())
        self.auto_state_display.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.auto_state_display.setFont(font)
        self.auto_state_display.setFocusPolicy(QtCore.Qt.NoFocus)
        self.auto_state_display.setAlignment(QtCore.Qt.AlignCenter)
        self.auto_state_display.setReadOnly(True)
        self.auto_state_display.setObjectName("auto_state_display")
        self.verticalLayout_3.addWidget(self.auto_state_display)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_4.addItem(spacerItem)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_21 = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_21.sizePolicy().hasHeightForWidth())
        self.label_21.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.verticalLayout.addWidget(self.label_21)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(Form)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.imu_angle = QtWidgets.QDoubleSpinBox(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.imu_angle.sizePolicy().hasHeightForWidth())
        self.imu_angle.setSizePolicy(sizePolicy)
        self.imu_angle.setDecimals(1)
        self.imu_angle.setMinimum(-180.0)
        self.imu_angle.setMaximum(180.0)
        self.imu_angle.setSingleStep(15.0)
        self.imu_angle.setObjectName("imu_angle")
        self.horizontalLayout_2.addWidget(self.imu_angle)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.set_imu_angle_button = QtWidgets.QPushButton(Form)
        self.set_imu_angle_button.setAutoFillBackground(False)
        self.set_imu_angle_button.setStyleSheet("background-color:#ff0000")
        self.set_imu_angle_button.setObjectName("set_imu_angle_button")
        self.verticalLayout.addWidget(self.set_imu_angle_button)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.n_balls_display = QtWidgets.QLabel(Form)
        self.n_balls_display.setObjectName("n_balls_display")
        self.verticalLayout_4.addWidget(self.n_balls_display)
        self.image_label = QtWidgets.QLabel(Form)
        self.image_label.setText("")
        self.image_label.setPixmap(QtGui.QPixmap(":/images/yellow_circle.png"))
        self.image_label.setObjectName("image_label")
        self.verticalLayout_4.addWidget(self.image_label)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Dialog"))
        self.dashLabel.setText(_translate("Form", "RQT Dashboard :)"))
        self.pubLabel.setText(_translate("Form", "Set Auto Mode"))
        self.label_2.setText(_translate("Form", "Auto Code Status"))
        self.auto_state_display.setText(_translate("Form", "Hello"))
        self.label_21.setText(_translate("Form", "Set IMU Angle"))
        self.label.setText(_translate("Form", "Angle (deg):"))
        self.set_imu_angle_button.setText(_translate("Form", "Set Angle"))
        self.n_balls_display.setText(_translate("Form", "Num Balls Display"))

import resource_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

