field_dims:
  x_min: 0
  x_max: 8.21
  y_min: 0
  y_max: 15.95

init_dims:
  x_min: 0
  x_max: 8
  y_min: 2
  y_max: 4

num_particles: 200

noise_stdev:
  position: 0.1
  rotation: 0.1

beacons:
  - [2.40, 0.0]
  - [6.50, 0.0]
  - [1.71, 15.98]
  - [5.81, 15.98]
