noise_delta_t: 1.0

field_dims:
  x_min: 0.0
  x_max: 4.0
  y_min: 0.0
  y_max: 4.0

init_dims:
  x_min: 0.0
  x_max: 4.0
  y_min: 0.0
  y_max: 4.0

num_particles: 100

noise_stdev:
  position: 0.1
  rotation: 0.1

beacons:
  - [3.0, 3.0]
  - [3.0, 2.0]
  - [4.0, 1.0]
